# Generated by Django 4.2.7 on 2023-12-01 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='blogs/')),
                ('image_alt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('albania', 'Albania'), ('andorra', 'Andorra'), ('austria', 'Austria'), ('belarus', 'Belarus'), ('belgium', 'Belgium'), ('bosnia-and-herzegovina', 'Bosnia and Herzegovina'), ('bulgaria', 'Bulgaria'), ('croatia', 'Croatia'), ('cyprus', 'Cyprus'), ('czech-republic', 'Czech Republic'), ('denmark', 'Denmark'), ('estonia', 'Estonia'), ('finland', 'Finland'), ('germany', 'Germany'), ('greece', 'Greece'), ('hungary', 'Hungary'), ('iceland', 'Iceland'), ('ireland', 'Ireland'), ('italy', 'Italy'), ('kosovo', 'Kosovo'), ('latvia', 'Latvia'), ('liechtenstein', 'Liechtenstein'), ('lithuania', 'Lithuania'), ('luxembourg', 'Luxembourg'), ('malta', 'Malta'), ('moldova', 'Moldova'), ('monaco', 'Monaco'), ('montenegro', 'Montenegro'), ('netherlands', 'Netherlands'), ('north-macedonia', 'North Macedonia'), ('norway', 'Norway'), ('poland', 'Poland'), ('portugal', 'Portugal'), ('romania', 'Romania'), ('russia', 'Russia'), ('san-marino', 'San Marino'), ('serbia', 'Serbia'), ('slovakia', 'Slovakia'), ('slovenia', 'Slovenia'), ('spain', 'Spain'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('ukraine', 'Ukraine'), ('united-kingdom', 'United Kingdom'), ('vatican-city', 'Vatican City')], default='afford', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
